mail.smtp.host=mail.hiroya-akiba.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.user=todoapp_auth
mail.smtp.password=T0d0@pp_aUth
mail.smtp.from=todoapp_auth@hiroya-akiba.com
